---
title: "Comparison to epiworld"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Comparison to epiworld}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(multigroup.vaccine)
library(epiworldR)
```

```{r}
pops <- c(60, 100, 500)
R0 <- 1.5
meaninf <- 7
incontact <- c(0.8, 0.8, 0.8)
f <- (1 - incontact) * pops
cmat <- (diag(incontact) + outer((1 - incontact), f / sum(f)))

betaij <- transmissionRates(
  R0 = R0,
  meaninf = meaninf,
  reltransm = cmat
)

ode_size <- multigroup.vaccine::getFinalSizeODE(
  transmrates = betaij,
  recoveryrate = 1 / meaninf,
  popsize = pops,
  initR = rep(0, 3),
  initI = c(1, 0, 0),
  initV = rep(0, 3)
)

fsODE <- sum(ode_size$totalSize)
```

```{r}
numsims <- 100
getFSD <- function(n, initI){
  multigroup.vaccine::getFinalSizeDist(
    n = n,
    transmrates = betaij,
    recoveryrate = 1 / meaninf,
    popsize = pops,
    initR = rep(0, length(pops)),
    initV = rep(0, length(pops)),
    initI = initI
  )
}
initIcounts <- tabulate(sample(length(pops), numsims, replace = TRUE, prob = pops))
ind <- c(0, cumsum(initIcounts))
size_dist <- matrix(0, numsims, length(pops))
for (i in seq_along(initIcounts)) {
  if (initIcounts[i] > 0) {
    initI <- rep(0, length(pops))
    initI[i] <- 1
    size_dist[(ind[i] + 1):ind[i + 1], ] <- getFSD(initIcounts[i], initI)
  }
}
fs1 <- rowSums(size_dist)
```

```{r}
abm_model <- ModelSEIRMixing(
  name = "abc",
  n = sum(pops),
  prevalence = 1 / sum(pops),
  contact_rate = R0 * (1 / meaninf) / .1,
  recovery_rate = 1 / meaninf,
  contact_matrix = cmat,
  transmission_rate = .1,
  incubation_days = 0
)

# Start off creating three entities.
# Individuals will be distribured randomly between the three.
e1 <- entity("Population 1", pops[1], as_proportion = FALSE)
e2 <- entity("Population 2", pops[2], as_proportion = FALSE)
e3 <- entity("Population 3", pops[3], as_proportion = FALSE)

abm_model |>
  add_entity(e1) |>
  add_entity(e2) |>
  add_entity(e3)

# Creating the saver
saver <- make_saver("total_hist", "reproductive")

# Running multiple simulations
ndays <- 400
# nthr <- parallel::detectCores() - 1L
run_multiple(m = abm_model, ndays = ndays, nsims = numsims, saver = saver, nthreads = 1)
res <- run_multiple_get_results(abm_model, nthreads = 1)
total_hist <- res$total_hist
final_day <- total_hist[total_hist$date == ndays, ]
fs2 <- final_day$counts[final_day$state == "Recovered"]

getdiststats <- function(fs) {
  c(median = median(fs), mean = mean(fs), meanHigh = mean(fs[fs > fsODE / 2]))
}

c(finalSizeODE = fsODE)
rbind(finalSizeGillespie = getdiststats(fs1), finalSizeEpiworld = getdiststats(fs2))
```
