---
title: "Measles Outbreak Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Measles Outbreak Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(multigroup.vaccine)
library(epiworldR)
```

```{r}
pops <- c(414, 37, 987, 647, 944, 190, 594, 131, 133, 1133, 632, 604, 221, 512, 511, 29,
  548, 232, 110, 2296, 98, 1218, 742, 582, 1352, 173, 41, 11)

initV <- c(371, 36, 913, 578, 905, 168, 420, 97, 117, 1072, 581, 555, 201, 489, 469, 19,
  509, 219, 103, 1143, 95, 786, 431, 517, 1276, 113, 29, 11)

countypop <- 64000
othervaxrate <- 0.95
pops <- c(pops, countypop - sum(pops))
initV <- c(initV, round(othervaxrate * pops[length(pops)]))

initI <- rep(0, length(pops))
initI[20] <- 1
initR <- rep(0, length(pops))

R0 <- 15
meaninf <- 7
incontact <- rep(0.8, length(pops))
f <- (1 - incontact) * pops
cmat <- (diag(incontact) + outer((1 - incontact), f / sum(f)))

betaij <- transmissionRates(
  R0 = R0,
  meaninf = meaninf,
  reltransm = cmat
)

ode_size <- multigroup.vaccine::getFinalSizeODE(
  transmrates = betaij,
  recoveryrate = 1 / meaninf,
  popsize = pops,
  initR = initR,
  initI = initI,
  initV = initV
)

fsODE <- sum(ode_size$totalSize)
```

```{r}
numsims <- 1000
size_dist <- getFinalSizeDist(
  n = numsims,
  transmrates = betaij,
  recoveryrate = 1 / meaninf,
  popsize = pops,
  initR = initR,
  initV = initV,
  initI = initI)

fs1 <- rowSums(size_dist)
hist(fs1, breaks = 50)
```
