---
title: "Threading Speed Test"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Threading Speed Test}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
For testing if multi-threading speeds up stochastic simulations

```{r setup}
library(multigroup.vaccine)
```

Large population:

```{r}
popsize <- rep(100000, 10)
```

Generic simulation settings - expect long simulations with R0 = 4 and no immunity
```{r}
relcontact <- rep(1, 10)
incontact <- rep(0.2, 10)
contactmatrix <- contactMatrixPropPref(popsize, relcontact, incontact)
relsusc <- rep(1, 10)
reltransm <- rep(1, 10)
R0 <- 4
initR <- rep(0, 10)
initI <- rep(1, 10)
initV <- rep(0, 10)
```

Final outbreak size (stochastic method)

Time of simulation with 1 thread:
```{r}
tm1 <- Sys.time()
fs1 <- finalsize(popsize, R0, contactmatrix, relsusc, reltransm, initR, initI, initV,
                method = "stochastic", nsims = 100, nthreads = 1, seed = 1111)
Sys.time() - tm1
```

Time of simulation with 2 threads:
```{r}
tm2 <- Sys.time()
fs2 <- finalsize(popsize, R0, contactmatrix, relsusc, reltransm, initR, initI, initV,
                 method = "stochastic", nsims = 100, nthreads = 2, seed = 1111)
Sys.time() - tm2
```

Time of simulation with 3 threads:
```{r}
tm3 <- Sys.time()
fs3 <- finalsize(popsize, R0, contactmatrix, relsusc, reltransm, initR, initI, initV,
                method = "stochastic", nsims = 100, nthreads = 3, seed = 1111)
Sys.time() - tm3
```
Time of simulation with 4 threads:
```{r}
tm4 <- Sys.time()
fs4 <- finalsize(popsize, R0, contactmatrix, relsusc, reltransm, initR, initI, initV,
                method = "stochastic", nsims = 100, nthreads = 4, seed = 1111)
Sys.time() - tm4
```
