# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sir_ssa_cpp <- function(state, beta, gamma, tmax) {
    .Call(`_multigroup_vaccine_sir_ssa_cpp`, state, beta, gamma, tmax)
}

