# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sir_finalsize_cpp <- function(init, beta, gamma) {
    .Call(`_multigroup_vaccine_sir_finalsize_cpp`, init, beta, gamma)
}

